"""
Report generator — produces formatted markdown maturity reports
from FrameworkResult objects.
"""

from scorer import FrameworkResult, score_bar


def generate_report(result: FrameworkResult) -> str:
    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        f"# {result.framework_name} — Maturity Assessment Report",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Organization | {result.org} |",
        f"| Assessor | {result.assessor} |",
        f"| Date | {result.date} |",
        f"| Framework | {result.framework_name} |",
        "",
        "---",
        "",
        "## Overall Maturity Score",
        "",
        f"```",
        f"  Score:    {result.overall_score:.1f} / 5.0",
        f"  Level:    {result.maturity_name}",
        f"  Progress: [{score_bar(result.overall_score)}] {result.overall_score:.1f}/5.0",
        f"```",
        "",
        f"> {result.maturity_desc}",
        "",
        "---",
        "",
        "## Domain Scores",
        "",
    ]

    # ── Domain table ──────────────────────────────────────────────────────────
    lines.append("| Domain | Score | Target | Gap | Level |")
    lines.append("|--------|-------|--------|-----|-------|")
    for d in result.domains:
        gap_str = f"-{d.gap:.1f}" if d.gap > 0 else "On target"
        lines.append(f"| {d.label} | {d.weighted_score:.1f} | {d.target_score:.1f} | {gap_str} | {d.maturity_name} |")

    lines += ["", "---", "", "## Domain Detail", ""]

    # ── Domain detail ─────────────────────────────────────────────────────────
    for d in result.domains:
        lines += [
            f"### {d.label}",
            "",
            f"**Score:** {d.weighted_score:.1f} / 5.0 — **{d.maturity_name}**",
            f"`[{score_bar(d.weighted_score)}]`",
            "",
            "| Sub-domain / Control | Score | Target | Gap | Level |",
            "|----------------------|-------|--------|-----|-------|",
        ]
        for sd in d.subdomains:
            gap_str = f"-{sd.gap:.1f}" if sd.gap > 0 else "Met"
            lines.append(f"| {sd.label} | {sd.score:.1f} | {sd.target:.1f} | {gap_str} | {sd.maturity_name} |")
        lines.append("")

    # ── Gap analysis ──────────────────────────────────────────────────────────
    lines += ["---", "", "## Priority Gap Analysis", ""]

    if result.gaps:
        lines += [
            "Controls with the largest gaps from target — address in order.",
            "",
            "| # | Control / Sub-domain | Current | Target | Gap |",
            "|---|----------------------|---------|--------|-----|",
        ]
        for i, g in enumerate(result.gaps[:10], 1):
            lines.append(f"| {i} | {g.label} | {g.score:.1f} | {g.target:.1f} | -{g.gap:.1f} |")
    else:
        lines.append("No significant gaps identified. All domains within 0.5 of target.")

    # ── Remediation guidance ──────────────────────────────────────────────────
    lines += ["", "---", "", "## Remediation Guidance", ""]

    remediation_map = _get_remediation_map(result.framework_id)
    shown = 0
    for g in result.gaps[:5]:
        guidance = remediation_map.get(g.key)
        if guidance:
            lines += [f"**{g.label}** (Gap: -{g.gap:.1f})", "", f"{guidance}", ""]
            shown += 1

    if shown == 0:
        lines.append("No specific remediation guidance available for current gaps.")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        f"*Generated by OrionMaturity Scoring Engine — {result.date}*",
        "",
    ]

    return "\n".join(lines)


def _get_remediation_map(framework_id: str) -> dict:
    if framework_id == "nist_csf_2":
        return {
            "risk_assessment":    "Formalize risk assessment cadence (quarterly minimum). Implement quantitative risk scoring — see CRQ-F methodology. Map identified risks to controls and track residual risk.",
            "supply_chain_risk":  "Build a third-party AI/software inventory. Deploy vendor DDQ process. Tier suppliers by risk level and set re-assessment schedules.",
            "anomalies_events":   "Tune SIEM correlation rules. Add UEBA for behavioral baselining. Define alert thresholds with documented rationale.",
            "incident_management":"Document and test incident response playbooks. Run tabletop exercises quarterly. Define RACI for incident roles.",
            "policy_governance":  "Conduct annual policy review cycle. Assign policy owners. Track exceptions formally.",
            "recovery_planning":  "Document and test recovery plans annually. Define RTO/RPO per system. Automate backup validation.",
        }
    elif framework_id == "cis_v8":
        return {
            "CIS01": "Deploy automated asset discovery (e.g., Axonius, Runscope). Integrate with CMDB. Set discovery scan cadence to weekly minimum.",
            "CIS05": "Implement IGA platform (e.g., SailPoint, Saviynt). Automate joiner-mover-leaver workflows. Quarterly access certification campaigns.",
            "CIS07": "Deploy vulnerability scanner with authenticated scanning. Establish SLA-based remediation targets (Critical: 15 days, High: 30 days). Track MTTM metric.",
            "CIS11": "Implement automated backup with daily frequency and tested recovery. Document and test DR runbooks. Target RTO < 4 hours for critical systems.",
            "CIS13": "Deploy NDR or network-based anomaly detection. Define network segmentation policy. Enable east-west traffic inspection.",
            "CIS17": "Build and test incident response playbooks per threat scenario. Implement SOAR for automation. Define escalation matrix and comms templates.",
        }
    elif framework_id == "iso_27001":
        return {
            "threat_intel":  "Subscribe to a commercial threat intelligence platform (e.g., Recorded Future, MISP). Integrate TI feeds into SIEM. Define TI consumer roles.",
            "iam":           "Enforce MFA for all privileged access. Implement PAM solution. Conduct quarterly access reviews. Enforce least privilege on all roles.",
            "logging":       "Centralize log management into SIEM. Define log retention policy (12 months minimum). Implement integrity monitoring on log infrastructure.",
            "vuln_mgmt":     "Establish vulnerability management program with SLA-based remediation. Deploy authenticated scanning. Track CVaR metric for board reporting.",
            "sdlc":          "Integrate SAST/DAST into CI/CD pipeline. Train developers on OWASP Top 10. Define secure coding standards and conduct annual code review.",
            "policies":      "Establish annual policy review cycle with named owners. Track policy exceptions formally. Align policy language to regulatory requirements.",
        }
    return {}
